#!/usr/bin/env python3
"""
Rebuild ~/vault/rules.md from per-rule files in ~/vault/rules/*.md.

Reads every *.md in ~/vault/rules/ (excluding README.md and rules.md itself),
parses frontmatter (title, scope, priority, status), emits a single index
file with H2 sections per scope, rules sorted by priority (high → normal → low)
then alphabetically.

Excludes rules with status: archived or status: superseded.

Env:
  VAULT_DIR   override vault path (default ~/vault)

Exit codes:
  0 on success, non-zero on parse error.
"""
from __future__ import annotations
import os, re, sys, pathlib, datetime

VAULT = pathlib.Path(os.environ.get("VAULT_DIR", pathlib.Path.home() / "vault"))
RULES_DIR = VAULT / "rules"
INDEX = VAULT / "rules.md"
TODAY = datetime.date.today().isoformat()

FM_RE = re.compile(r"\A---\n(.*?)\n---\n?(.*)\Z", re.DOTALL)
PRIORITY_ORDER = {"high": 0, "normal": 1, "low": 2}
SKIP_FILES = {"README.md", "rules.md", ".config.yml", ".config.example.yml"}


def parse_frontmatter(text: str):
    m = FM_RE.match(text)
    if not m:
        return {}, text
    fm = {}
    for line in m.group(1).splitlines():
        mm = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", line)
        if mm:
            fm[mm.group(1)] = mm.group(2).strip()
    return fm, m.group(2)


def parse_scope(raw: str) -> list[str]:
    raw = raw.strip()
    if raw.startswith("[") and raw.endswith("]"):
        return [s.strip().strip('"\'') for s in raw[1:-1].split(",") if s.strip()]
    return [raw.strip('"\'')] if raw else ["global"]


def is_empty_body(body: str) -> bool:
    """Return True if the body has no real content (only whitespace / blank lines)."""
    return body.strip() == ""


def load_rules():
    rules = []
    if not RULES_DIR.is_dir():
        return rules
    for f in sorted(RULES_DIR.glob("*.md")):
        if f.name in SKIP_FILES or f.name.startswith("."):
            continue
        try:
            text = f.read_text(encoding="utf-8")
        except OSError as e:
            print(f"warn: cannot read {f}: {e}", file=sys.stderr)
            continue
        fm, body = parse_frontmatter(text)
        if fm.get("status", "active") in ("archived", "superseded"):
            continue
        if is_empty_body(body):
            # Rule files with no body — skip. Do NOT delete; user may be about to fill in via /add-rule.
            continue
        rules.append({
            "path": f,
            "title": fm.get("title", f.stem).strip('"\''),
            "scopes": parse_scope(fm.get("scope", "global")),
            "priority": fm.get("priority", "normal"),
            "body": body.strip(),
        })
    return rules


def render(rules):
    by_scope: dict[str, list] = {}
    for r in rules:
        for s in r["scopes"]:
            by_scope.setdefault(s, []).append(r)

    scope_order = sorted(
        by_scope.keys(),
        key=lambda s: (s != "global", s.startswith("tool:"), s),
    )

    lines = [
        "---",
        "title: Rules — Map of Active Behaviors",
        f"updated: {TODAY}",
        "type: moc",
        "---",
        "",
        "# Rules — Map of Active Behaviors",
        "",
        "> Auto-generated by `~/scripts/rules_rebuild.py`. Do not hand-edit — edit the per-rule files in `~/vault/rules/` instead.",
        "",
    ]

    for scope in scope_order:
        lines.append(f"## scope: {scope}")
        lines.append("")
        entries = sorted(
            by_scope[scope],
            key=lambda r: (PRIORITY_ORDER.get(r["priority"], 1), r["title"].lower()),
        )
        for r in entries:
            lines.append(f"### [[{r['path'].stem}|{r['title']}]]")
            lines.append(f"*priority: {r['priority']}*")
            lines.append("")
            lines.append(r["body"])
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main():
    rules = load_rules()
    out = render(rules)
    INDEX.parent.mkdir(parents=True, exist_ok=True)
    INDEX.write_text(out, encoding="utf-8")
    print(f"wrote {INDEX} ({len(rules)} rules across {len({s for r in rules for s in r['scopes']})} scopes)")


if __name__ == "__main__":
    main()
