#!/usr/bin/env python3
"""
Rebuild every _MOC.md from note frontmatter + filesystem state.

For each group in ~/vault/.groups:
  - Scan <group>/*.md (and <group>/logs/*.md if present)
  - Emit <group>/_MOC.md: flat alphabetical "## Notes" section plus
    optional "## Recent logs (last 20)" section

For the shared MOC at ~/vault/_MOC.md:
  - Scan permanent/*.md + inbox/*.md
  - Emit "## Permanent notes" and "## Inbox (awaiting promotion)" sections

Description for each entry: frontmatter `description:` if present,
else first non-empty / non-heading line of body, trimmed to 120 chars.

Preserves the existing `created:` date; stamps `updated:` to today.

Env:
  VAULT_DIR   override vault path (default ~/vault)
"""
from __future__ import annotations
import os, re, sys, pathlib, datetime

VAULT = pathlib.Path(os.environ.get("VAULT_DIR", pathlib.Path.home() / "vault"))
GROUPS_FILE = VAULT / ".groups"
TODAY = datetime.date.today().isoformat()

FM_RE = re.compile(r"\A---\n(.*?)\n---\n?(.*)\Z", re.DOTALL)


def parse_frontmatter(text: str):
    m = FM_RE.match(text)
    if not m:
        return {}, text
    fm: dict[str, str] = {}
    for line in m.group(1).splitlines():
        mm = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", line)
        if mm:
            fm[mm.group(1)] = mm.group(2).strip()
    return fm, m.group(2)


def extract_tags(fm: dict) -> list[str]:
    raw = fm.get("tags", "")
    if raw.startswith("[") and raw.endswith("]"):
        return [t.strip().strip('"\'') for t in raw[1:-1].split(",") if t.strip()]
    return []


def description(fm: dict, body: str, limit: int = 140) -> str:
    desc = fm.get("description", "").strip('"\'').strip()
    if not desc:
        for line in body.splitlines():
            s = line.strip()
            if not s or s.startswith(("#", ">", "---", "```", "- [[")):
                continue
            desc = s
            break
    if not desc:
        return ""
    if len(desc) <= limit:
        return desc
    cut = desc[:limit].rsplit(" ", 1)[0].rstrip(",.;:—-")
    return cut + "…"


def collect_notes(paths: list[pathlib.Path]) -> tuple[list[dict], list[dict]]:
    notes, logs = [], []
    for base in paths:
        if not base.exists() or not base.is_dir():
            continue
        for p in sorted(base.rglob("*.md")):
            if p.name == "_MOC.md":
                continue
            if any(part.startswith(".") or part == "templates" for part in p.parts):
                continue
            try:
                text = p.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            fm, body = parse_frontmatter(text)
            entry = {
                "stem": p.stem,
                "title": fm.get("title", p.stem),
                "desc": description(fm, body),
                "tags": extract_tags(fm),
                "type": fm.get("type", ""),
                "mtime": p.stat().st_mtime,
                "path": p,
            }
            if fm.get("type") == "log" or "logs" in p.parts:
                logs.append(entry)
            elif fm.get("type") == "moc":
                continue
            else:
                notes.append(entry)
    return notes, logs


def render_moc(
    *,
    title: str,
    group: str,
    notes: list[dict],
    logs: list[dict],
    notes_heading: str = "Notes",
    extra_sections: list[tuple[str, list[dict]]] | None = None,
    existing_created: str | None = None,
) -> str:
    lines = [
        "---",
        f"title: {title}",
        f"group: {group}",
        f"tags: [{group}, moc]",
        "type: moc",
        f"created: {existing_created or TODAY}",
        f"updated: {TODAY}",
        "---",
        "",
        f"# {title}",
        "",
        "> Auto-generated by `vault_rebuild_mocs.py`. Edit each note's frontmatter (`description:`, `tags:`) to change how it appears here.",
        "",
    ]

    def section(heading: str, items: list[dict], sort_key=lambda x: x["title"].lower()):
        if not items:
            return
        lines.append(f"## {heading}")
        lines.append("")
        for n in sorted(items, key=sort_key):
            row = f"- [[{n['stem']}]]"
            if n["desc"]:
                row += f" — {n['desc']}"
            lines.append(row)
        lines.append("")

    section(notes_heading, notes)

    for heading, items in extra_sections or []:
        section(heading, items)

    if logs:
        lines.append("## Recent logs (last 20)")
        lines.append("")
        for l in sorted(logs, key=lambda x: x["stem"], reverse=True)[:20]:
            row = f"- [[{l['stem']}]]"
            if l["desc"]:
                row += f" — {l['desc']}"
            lines.append(row)
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def read_existing_created(path: pathlib.Path) -> str | None:
    if not path.exists():
        return None
    fm, _ = parse_frontmatter(path.read_text(encoding="utf-8", errors="ignore"))
    return fm.get("created") or None


def rebuild_shared():
    out = VAULT / "_MOC.md"
    permanent_notes, _ = collect_notes([VAULT / "permanent"])
    inbox_notes, _ = collect_notes([VAULT / "inbox"])
    content = render_moc(
        title="Vault MOC (shared)",
        group="shared",
        notes=permanent_notes,
        logs=[],
        notes_heading="Permanent notes",
        extra_sections=[("Inbox (awaiting promotion)", inbox_notes)] if inbox_notes else None,
        existing_created=read_existing_created(out),
    )
    out.write_text(content, encoding="utf-8")
    print(f"wrote {out.relative_to(VAULT)} ({len(permanent_notes)} permanent, {len(inbox_notes)} inbox)")


def rebuild_group(group: str):
    base = VAULT / group
    if not base.is_dir():
        return
    out = base / "_MOC.md"
    notes, logs = collect_notes([base])
    content = render_moc(
        title=f"{group.capitalize()} — Map of Contents",
        group=group,
        notes=notes,
        logs=logs,
        existing_created=read_existing_created(out),
    )
    out.write_text(content, encoding="utf-8")
    print(f"wrote {out.relative_to(VAULT)} ({len(notes)} notes, {len(logs)} logs)")


def main():
    groups = []
    if GROUPS_FILE.exists():
        groups = [l.strip() for l in GROUPS_FILE.read_text().splitlines() if l.strip() and not l.startswith("#")]
    rebuild_shared()
    for g in groups:
        rebuild_group(g)


if __name__ == "__main__":
    main()
